#version: 2
#jobs:
#  build:
#    working_directory: ~/myapp/angular-whishlist
#    docker:
#      - image: circleci/node:12-browsers
#    steps:
#      - checkout:
#          path: ~/myapp
 #     - restore_cache:
 #         key: angular-whishlist-{{ .Branch }}-{{ checksum "package-lock.json" }}
 #     - run: npm install
 #     - save_cache:
#          key: angular-whishlist-{{ .Branch }}-{{ checksum "package-lock.json" }}
#          paths:
#            - "node_modules"
#      - run: npm run test -- --progress=false --watch=false --browsers=ChromeHeadlessCI --source-map=false


version: 2
jobs:
  build:
    working_directory: ~/angular-whishlist
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-whishlist-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: angular-whishlist-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
#      - run: xvfb-run -a npm run test -- --watch=false --no-progress --browser=ChromeNoSandbox
#      - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
      - run: xvfb-run -a npm run test -- --progress=false --watch=false --browsers=ChromeHeadlessCI --source-map=false